#!/bin/bash
# publish build assets in `/dist/` to `dist` branch
set -xeuo pipefail
cd "`dirname "$0"`/../.."

# build the files that should be in the branch.
rm -rf ./build
mkdir -p ./build/dist
# `git archive` copies all files currently in git to a tar file.
git archive -o ./build/dist.tar --format tar HEAD
# `git archive` skips `.gitignore`d files (and locally modified files), but the
# whole point of this is to publish `dist`, so add it manually.
# cp -rp ./dist ./build/dist/dist
tar -f ./build/dist.tar --append dist
# Print the contents
tar -tf ./build/dist.tar
# Extract to a directory
tar -xf ./build/dist.tar -C ./build/dist

# Create a temporary git repository to publish the results.
cd ./build/dist
PUBLISH_BRANCH="dist"
ORIGIN=`git remote get-url origin`
NAME="dist-publishing robot"
MAIL="erosson+actions@users.noreply.github.com>"
#BRANCH=`git branch --show-current`
git init
git remote add origin "$ORIGIN"
git fetch origin "$PUBLISH_BRANCH"
git branch -r
# checkout, using remote history, without changing local files
git reset "origin/$PUBLISH_BRANCH"
git checkout -b "$PUBLISH_BRANCH"
# add local files
git add .
git add dist -f
git status
git -c user.name="$NAME" -c user.email="$MAIL" commit --allow-empty -m 'automated dist update'
git push origin "$PUBLISH_BRANCH"
rm -rf .git/