#!/bin/bash
# publish documentation in `/docs/` to `gh-pages` branch
# https://erosson.github.io/json-codec/
set -xeuo pipefail
cd "`dirname "$0"`/../.."

cd ./docs
rm -rf .git/
PUBLISH_BRANCH="gh-pages"
ORIGIN="${ORIGIN:-`git remote get-url origin`}"
NAME="docs-publishing robot"
MAIL="erosson+actions@users.noreply.github.com>"
# BRANCH=`git branch --show-current`
git init
git remote add origin "$ORIGIN"
git checkout -b "$PUBLISH_BRANCH"
git add .
git -c user.name="$NAME" -c user.email="$MAIL" commit -m 'automated docs update'
git push -f origin "$PUBLISH_BRANCH"
rm -rf .git/