#!/bin/bash
# publish documentation in `/docs/` to `gh-pages` branch
# https://erosson.github.io/json-encode-decode/
set -xeuo pipefail
cd "`dirname "$0"`/../.."

cd ./docs
rm -rf .git/
PUBLISH_BRANCH="gh-pages"
ORIGIN=`git remote get-url origin`
USER="docs-publising robot"
MAIL="erosson+actions@users.noreply.github.com>"
# BRANCH=`git branch --show-current`
git init
git checkout -b "$PUBLISH_BRANCH"
git add .
git -c user.name="$NAME" -c user.email="$MAIL" commit -m 'automated docs update'
git push -f "$ORIGIN" "$PUBLISH_BRANCH"
rm -rf .git/