name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: "Build, test, publish dist and gh-pages"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - run: yarn --dev --frozen-lockfile
      - run: yarn build
      - run: yarn publish:dist
      - run: yarn publish:docs
