name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: "Build, test, publish dist and gh-pages"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - run: yarn --dev --frozen-lockfile
      - run: yarn build
      - run: yarn publish:dist
        env:
          ORIGIN: "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
      - run: yarn publish:docs
        env:
          ORIGIN: "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
